version: "3.7"

services:
  db:
    container_name: "house-hunter-db"
    restart: "always"
    image: "postgres:latest"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres:/data/house-hunter

networks:
  db:

volumes:
  postgres:
